/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetcher } from ".././fetcher";
import type {
	ActivityEventsResponse,
	ActivityListResponse,
	HTTPValidationError,
	ListActivitiesApiActivitiesGetParams,
	ManualActivityCreateRequest,
	ManualActivityCreateResponse,
} from ".././schemas";

/**
 * 获取活动列表（活动=聚合的事件窗口）
 * @summary List Activities
 */
export const listActivitiesApiActivitiesGet = (
	params?: ListActivitiesApiActivitiesGetParams,
	signal?: AbortSignal,
) => {
	return customFetcher<ActivityListResponse>({
		url: `/api/activities`,
		method: "GET",
		params,
		signal,
	});
};

export const getListActivitiesApiActivitiesGetQueryKey = (
	params?: ListActivitiesApiActivitiesGetParams,
) => {
	return [`/api/activities`, ...(params ? [params] : [])] as const;
};

export const getListActivitiesApiActivitiesGetQueryOptions = <
	TData = Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
	TError = HTTPValidationError,
>(
	params?: ListActivitiesApiActivitiesGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getListActivitiesApiActivitiesGetQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>
	> = ({ signal }) => listActivitiesApiActivitiesGet(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListActivitiesApiActivitiesGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>
>;
export type ListActivitiesApiActivitiesGetQueryError = HTTPValidationError;

export function useListActivitiesApiActivitiesGet<
	TData = Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
	TError = HTTPValidationError,
>(
	params: undefined | ListActivitiesApiActivitiesGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
					TError,
					Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListActivitiesApiActivitiesGet<
	TData = Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
	TError = HTTPValidationError,
>(
	params?: ListActivitiesApiActivitiesGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
					TError,
					Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListActivitiesApiActivitiesGet<
	TData = Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
	TError = HTTPValidationError,
>(
	params?: ListActivitiesApiActivitiesGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Activities
 */

export function useListActivitiesApiActivitiesGet<
	TData = Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
	TError = HTTPValidationError,
>(
	params?: ListActivitiesApiActivitiesGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listActivitiesApiActivitiesGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListActivitiesApiActivitiesGetQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 获取指定活动关联的事件ID列表
 * @summary Get Activity Events
 */
export const getActivityEventsApiActivitiesActivityIdEventsGet = (
	activityId: number,
	signal?: AbortSignal,
) => {
	return customFetcher<ActivityEventsResponse>({
		url: `/api/activities/${activityId}/events`,
		method: "GET",
		signal,
	});
};

export const getGetActivityEventsApiActivitiesActivityIdEventsGetQueryKey = (
	activityId?: number,
) => {
	return [`/api/activities/${activityId}/events`] as const;
};

export const getGetActivityEventsApiActivitiesActivityIdEventsGetQueryOptions =
	<
		TData = Awaited<
			ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
		>,
		TError = HTTPValidationError,
	>(
		activityId: number,
		options?: {
			query?: Partial<
				UseQueryOptions<
					Awaited<
						ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
					>,
					TError,
					TData
				>
			>;
		},
	) => {
		const { query: queryOptions } = options ?? {};

		const queryKey =
			queryOptions?.queryKey ??
			getGetActivityEventsApiActivitiesActivityIdEventsGetQueryKey(activityId);

		const queryFn: QueryFunction<
			Awaited<
				ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
			>
		> = ({ signal }) =>
			getActivityEventsApiActivitiesActivityIdEventsGet(activityId, signal);

		return {
			queryKey,
			queryFn,
			enabled: !!activityId,
			...queryOptions,
		} as UseQueryOptions<
			Awaited<
				ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
			>,
			TError,
			TData
		> & { queryKey: DataTag<QueryKey, TData, TError> };
	};

export type GetActivityEventsApiActivitiesActivityIdEventsGetQueryResult =
	NonNullable<
		Awaited<
			ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
		>
	>;
export type GetActivityEventsApiActivitiesActivityIdEventsGetQueryError =
	HTTPValidationError;

export function useGetActivityEventsApiActivitiesActivityIdEventsGet<
	TData = Awaited<
		ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
	>,
	TError = HTTPValidationError,
>(
	activityId: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
				>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<
						ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
					>,
					TError,
					Awaited<
						ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
					>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetActivityEventsApiActivitiesActivityIdEventsGet<
	TData = Awaited<
		ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
	>,
	TError = HTTPValidationError,
>(
	activityId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
				>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<
						ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
					>,
					TError,
					Awaited<
						ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
					>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetActivityEventsApiActivitiesActivityIdEventsGet<
	TData = Awaited<
		ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
	>,
	TError = HTTPValidationError,
>(
	activityId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
				>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Activity Events
 */

export function useGetActivityEventsApiActivitiesActivityIdEventsGet<
	TData = Awaited<
		ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
	>,
	TError = HTTPValidationError,
>(
	activityId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<typeof getActivityEventsApiActivitiesActivityIdEventsGet>
				>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getGetActivityEventsApiActivitiesActivityIdEventsGetQueryOptions(
			activityId,
			options,
		);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 手动聚合指定事件集合为活动

Args:
    request: 包含事件ID列表的请求

Returns:
    创建的活动信息
 * @summary Create Activity Manual
 */
export const createActivityManualApiActivitiesManualPost = (
	manualActivityCreateRequest: ManualActivityCreateRequest,
	signal?: AbortSignal,
) => {
	return customFetcher<ManualActivityCreateResponse>({
		url: `/api/activities/manual`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: manualActivityCreateRequest,
		signal,
	});
};

export const getCreateActivityManualApiActivitiesManualPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createActivityManualApiActivitiesManualPost>>,
		TError,
		{ data: ManualActivityCreateRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createActivityManualApiActivitiesManualPost>>,
	TError,
	{ data: ManualActivityCreateRequest },
	TContext
> => {
	const mutationKey = ["createActivityManualApiActivitiesManualPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createActivityManualApiActivitiesManualPost>>,
		{ data: ManualActivityCreateRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createActivityManualApiActivitiesManualPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateActivityManualApiActivitiesManualPostMutationResult =
	NonNullable<
		Awaited<ReturnType<typeof createActivityManualApiActivitiesManualPost>>
	>;
export type CreateActivityManualApiActivitiesManualPostMutationBody =
	ManualActivityCreateRequest;
export type CreateActivityManualApiActivitiesManualPostMutationError =
	HTTPValidationError;

/**
 * @summary Create Activity Manual
 */
export const useCreateActivityManualApiActivitiesManualPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createActivityManualApiActivitiesManualPost>>,
			TError,
			{ data: ManualActivityCreateRequest },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createActivityManualApiActivitiesManualPost>>,
	TError,
	{ data: ManualActivityCreateRequest },
	TContext
> => {
	const mutationOptions =
		getCreateActivityManualApiActivitiesManualPostMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
