/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { customFetcher } from ".././fetcher";
import type {
	EventResponse,
	HTTPValidationError,
	ScreenshotResponse,
	SearchRequest,
} from ".././schemas";

/**
 * 搜索截图
 * @summary Search Screenshots
 */
export const searchScreenshotsApiSearchPost = (
	searchRequest: SearchRequest,
	signal?: AbortSignal,
) => {
	return customFetcher<ScreenshotResponse[]>({
		url: `/api/search`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: searchRequest,
		signal,
	});
};

export const getSearchScreenshotsApiSearchPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof searchScreenshotsApiSearchPost>>,
		TError,
		{ data: SearchRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof searchScreenshotsApiSearchPost>>,
	TError,
	{ data: SearchRequest },
	TContext
> => {
	const mutationKey = ["searchScreenshotsApiSearchPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof searchScreenshotsApiSearchPost>>,
		{ data: SearchRequest }
	> = (props) => {
		const { data } = props ?? {};

		return searchScreenshotsApiSearchPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SearchScreenshotsApiSearchPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof searchScreenshotsApiSearchPost>>
>;
export type SearchScreenshotsApiSearchPostMutationBody = SearchRequest;
export type SearchScreenshotsApiSearchPostMutationError = HTTPValidationError;

/**
 * @summary Search Screenshots
 */
export const useSearchScreenshotsApiSearchPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof searchScreenshotsApiSearchPost>>,
			TError,
			{ data: SearchRequest },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof searchScreenshotsApiSearchPost>>,
	TError,
	{ data: SearchRequest },
	TContext
> => {
	const mutationOptions =
		getSearchScreenshotsApiSearchPostMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 事件级简单文本搜索：按OCR分组后返回事件摘要
 * @summary Search Events
 */
export const searchEventsApiEventSearchPost = (
	searchRequest: SearchRequest,
	signal?: AbortSignal,
) => {
	return customFetcher<EventResponse[]>({
		url: `/api/event-search`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: searchRequest,
		signal,
	});
};

export const getSearchEventsApiEventSearchPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof searchEventsApiEventSearchPost>>,
		TError,
		{ data: SearchRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof searchEventsApiEventSearchPost>>,
	TError,
	{ data: SearchRequest },
	TContext
> => {
	const mutationKey = ["searchEventsApiEventSearchPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof searchEventsApiEventSearchPost>>,
		{ data: SearchRequest }
	> = (props) => {
		const { data } = props ?? {};

		return searchEventsApiEventSearchPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SearchEventsApiEventSearchPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof searchEventsApiEventSearchPost>>
>;
export type SearchEventsApiEventSearchPostMutationBody = SearchRequest;
export type SearchEventsApiEventSearchPostMutationError = HTTPValidationError;

/**
 * @summary Search Events
 */
export const useSearchEventsApiEventSearchPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof searchEventsApiEventSearchPost>>,
			TError,
			{ data: SearchRequest },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof searchEventsApiEventSearchPost>>,
	TError,
	{ data: SearchRequest },
	TContext
> => {
	const mutationOptions =
		getSearchEventsApiEventSearchPostMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
