/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetcher } from ".././fetcher";
import type {
	GetProjectTasksApiProjectsProjectIdTasksGetParams,
	GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetParams,
	GetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet200,
	HTTPValidationError,
	TaskBatchDeleteRequest,
	TaskBatchDeleteResponse,
	TaskCreate,
	TaskListResponse,
	TaskProgressListResponse,
	TaskProgressResponse,
	TaskResponse,
	TaskUpdate,
} from ".././schemas";

/**
 * 创建新任务

Args:
    project_id: 项目ID
    task: 任务创建信息

Returns:
    创建的任务信息
 * @summary Create Task
 */
export const createTaskApiProjectsProjectIdTasksPost = (
	projectId: number,
	taskCreate: TaskCreate,
	signal?: AbortSignal,
) => {
	return customFetcher<TaskResponse>({
		url: `/api/projects/${projectId}/tasks`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: taskCreate,
		signal,
	});
};

export const getCreateTaskApiProjectsProjectIdTasksPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createTaskApiProjectsProjectIdTasksPost>>,
		TError,
		{ projectId: number; data: TaskCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createTaskApiProjectsProjectIdTasksPost>>,
	TError,
	{ projectId: number; data: TaskCreate },
	TContext
> => {
	const mutationKey = ["createTaskApiProjectsProjectIdTasksPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createTaskApiProjectsProjectIdTasksPost>>,
		{ projectId: number; data: TaskCreate }
	> = (props) => {
		const { projectId, data } = props ?? {};

		return createTaskApiProjectsProjectIdTasksPost(projectId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateTaskApiProjectsProjectIdTasksPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof createTaskApiProjectsProjectIdTasksPost>>
>;
export type CreateTaskApiProjectsProjectIdTasksPostMutationBody = TaskCreate;
export type CreateTaskApiProjectsProjectIdTasksPostMutationError =
	HTTPValidationError;

/**
 * @summary Create Task
 */
export const useCreateTaskApiProjectsProjectIdTasksPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createTaskApiProjectsProjectIdTasksPost>>,
			TError,
			{ projectId: number; data: TaskCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createTaskApiProjectsProjectIdTasksPost>>,
	TError,
	{ projectId: number; data: TaskCreate },
	TContext
> => {
	const mutationOptions =
		getCreateTaskApiProjectsProjectIdTasksPostMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 获取项目的任务列表

Args:
    project_id: 项目ID
    limit: 返回数量限制
    offset: 偏移量

Returns:
    任务列表
 * @summary Get Project Tasks
 */
export const getProjectTasksApiProjectsProjectIdTasksGet = (
	projectId: number,
	params?: GetProjectTasksApiProjectsProjectIdTasksGetParams,
	signal?: AbortSignal,
) => {
	return customFetcher<TaskListResponse>({
		url: `/api/projects/${projectId}/tasks`,
		method: "GET",
		params,
		signal,
	});
};

export const getGetProjectTasksApiProjectsProjectIdTasksGetQueryKey = (
	projectId?: number,
	params?: GetProjectTasksApiProjectsProjectIdTasksGetParams,
) => {
	return [
		`/api/projects/${projectId}/tasks`,
		...(params ? [params] : []),
	] as const;
};

export const getGetProjectTasksApiProjectsProjectIdTasksGetQueryOptions = <
	TData = Awaited<
		ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	params?: GetProjectTasksApiProjectsProjectIdTasksGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetProjectTasksApiProjectsProjectIdTasksGetQueryKey(projectId, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>>
	> = ({ signal }) =>
		getProjectTasksApiProjectsProjectIdTasksGet(projectId, params, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!projectId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectTasksApiProjectsProjectIdTasksGetQueryResult =
	NonNullable<
		Awaited<ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>>
	>;
export type GetProjectTasksApiProjectsProjectIdTasksGetQueryError =
	HTTPValidationError;

export function useGetProjectTasksApiProjectsProjectIdTasksGet<
	TData = Awaited<
		ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	params: undefined | GetProjectTasksApiProjectsProjectIdTasksGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<
						ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
					>,
					TError,
					Awaited<
						ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
					>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectTasksApiProjectsProjectIdTasksGet<
	TData = Awaited<
		ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	params?: GetProjectTasksApiProjectsProjectIdTasksGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<
						ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
					>,
					TError,
					Awaited<
						ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
					>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectTasksApiProjectsProjectIdTasksGet<
	TData = Awaited<
		ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	params?: GetProjectTasksApiProjectsProjectIdTasksGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Tasks
 */

export function useGetProjectTasksApiProjectsProjectIdTasksGet<
	TData = Awaited<
		ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	params?: GetProjectTasksApiProjectsProjectIdTasksGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectTasksApiProjectsProjectIdTasksGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getGetProjectTasksApiProjectsProjectIdTasksGetQueryOptions(
			projectId,
			params,
			options,
		);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 获取单个任务详情

Args:
    project_id: 项目ID
    task_id: 任务ID

Returns:
    任务详情
 * @summary Get Task
 */
export const getTaskApiProjectsProjectIdTasksTaskIdGet = (
	projectId: number,
	taskId: number,
	signal?: AbortSignal,
) => {
	return customFetcher<TaskResponse>({
		url: `/api/projects/${projectId}/tasks/${taskId}`,
		method: "GET",
		signal,
	});
};

export const getGetTaskApiProjectsProjectIdTasksTaskIdGetQueryKey = (
	projectId?: number,
	taskId?: number,
) => {
	return [`/api/projects/${projectId}/tasks/${taskId}`] as const;
};

export const getGetTaskApiProjectsProjectIdTasksTaskIdGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetTaskApiProjectsProjectIdTasksTaskIdGetQueryKey(projectId, taskId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>
	> = ({ signal }) =>
		getTaskApiProjectsProjectIdTasksTaskIdGet(projectId, taskId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!(projectId && taskId),
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTaskApiProjectsProjectIdTasksTaskIdGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>
>;
export type GetTaskApiProjectsProjectIdTasksTaskIdGetQueryError =
	HTTPValidationError;

export function useGetTaskApiProjectsProjectIdTasksTaskIdGet<
	TData = Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
					TError,
					Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTaskApiProjectsProjectIdTasksTaskIdGet<
	TData = Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
					TError,
					Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTaskApiProjectsProjectIdTasksTaskIdGet<
	TData = Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Task
 */

export function useGetTaskApiProjectsProjectIdTasksTaskIdGet<
	TData = Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTaskApiProjectsProjectIdTasksTaskIdGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetTaskApiProjectsProjectIdTasksTaskIdGetQueryOptions(
		projectId,
		taskId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 更新任务

Args:
    project_id: 项目ID
    task_id: 任务ID
    task: 任务更新信息

Returns:
    更新后的任务信息
 * @summary Update Task
 */
export const updateTaskApiProjectsProjectIdTasksTaskIdPut = (
	projectId: number,
	taskId: number,
	taskUpdate: TaskUpdate,
) => {
	return customFetcher<TaskResponse>({
		url: `/api/projects/${projectId}/tasks/${taskId}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: taskUpdate,
	});
};

export const getUpdateTaskApiProjectsProjectIdTasksTaskIdPutMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateTaskApiProjectsProjectIdTasksTaskIdPut>>,
		TError,
		{ projectId: number; taskId: number; data: TaskUpdate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateTaskApiProjectsProjectIdTasksTaskIdPut>>,
	TError,
	{ projectId: number; taskId: number; data: TaskUpdate },
	TContext
> => {
	const mutationKey = ["updateTaskApiProjectsProjectIdTasksTaskIdPut"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateTaskApiProjectsProjectIdTasksTaskIdPut>>,
		{ projectId: number; taskId: number; data: TaskUpdate }
	> = (props) => {
		const { projectId, taskId, data } = props ?? {};

		return updateTaskApiProjectsProjectIdTasksTaskIdPut(
			projectId,
			taskId,
			data,
		);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateTaskApiProjectsProjectIdTasksTaskIdPutMutationResult =
	NonNullable<
		Awaited<ReturnType<typeof updateTaskApiProjectsProjectIdTasksTaskIdPut>>
	>;
export type UpdateTaskApiProjectsProjectIdTasksTaskIdPutMutationBody =
	TaskUpdate;
export type UpdateTaskApiProjectsProjectIdTasksTaskIdPutMutationError =
	HTTPValidationError;

/**
 * @summary Update Task
 */
export const useUpdateTaskApiProjectsProjectIdTasksTaskIdPut = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateTaskApiProjectsProjectIdTasksTaskIdPut>>,
			TError,
			{ projectId: number; taskId: number; data: TaskUpdate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateTaskApiProjectsProjectIdTasksTaskIdPut>>,
	TError,
	{ projectId: number; taskId: number; data: TaskUpdate },
	TContext
> => {
	const mutationOptions =
		getUpdateTaskApiProjectsProjectIdTasksTaskIdPutMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 删除任务

Args:
    project_id: 项目ID
    task_id: 任务ID

Returns:
    无返回内容
 * @summary Delete Task
 */
export const deleteTaskApiProjectsProjectIdTasksTaskIdDelete = (
	projectId: number,
	taskId: number,
) => {
	return customFetcher<void>({
		url: `/api/projects/${projectId}/tasks/${taskId}`,
		method: "DELETE",
	});
};

export const getDeleteTaskApiProjectsProjectIdTasksTaskIdDeleteMutationOptions =
	<TError = HTTPValidationError, TContext = unknown>(options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<typeof deleteTaskApiProjectsProjectIdTasksTaskIdDelete>
			>,
			TError,
			{ projectId: number; taskId: number },
			TContext
		>;
	}): UseMutationOptions<
		Awaited<ReturnType<typeof deleteTaskApiProjectsProjectIdTasksTaskIdDelete>>,
		TError,
		{ projectId: number; taskId: number },
		TContext
	> => {
		const mutationKey = ["deleteTaskApiProjectsProjectIdTasksTaskIdDelete"];
		const { mutation: mutationOptions } = options
			? options.mutation &&
				"mutationKey" in options.mutation &&
				options.mutation.mutationKey
				? options
				: { ...options, mutation: { ...options.mutation, mutationKey } }
			: { mutation: { mutationKey } };

		const mutationFn: MutationFunction<
			Awaited<
				ReturnType<typeof deleteTaskApiProjectsProjectIdTasksTaskIdDelete>
			>,
			{ projectId: number; taskId: number }
		> = (props) => {
			const { projectId, taskId } = props ?? {};

			return deleteTaskApiProjectsProjectIdTasksTaskIdDelete(projectId, taskId);
		};

		return { mutationFn, ...mutationOptions };
	};

export type DeleteTaskApiProjectsProjectIdTasksTaskIdDeleteMutationResult =
	NonNullable<
		Awaited<ReturnType<typeof deleteTaskApiProjectsProjectIdTasksTaskIdDelete>>
	>;

export type DeleteTaskApiProjectsProjectIdTasksTaskIdDeleteMutationError =
	HTTPValidationError;

/**
 * @summary Delete Task
 */
export const useDeleteTaskApiProjectsProjectIdTasksTaskIdDelete = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<typeof deleteTaskApiProjectsProjectIdTasksTaskIdDelete>
			>,
			TError,
			{ projectId: number; taskId: number },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteTaskApiProjectsProjectIdTasksTaskIdDelete>>,
	TError,
	{ projectId: number; taskId: number },
	TContext
> => {
	const mutationOptions =
		getDeleteTaskApiProjectsProjectIdTasksTaskIdDeleteMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 批量删除任务

Args:
    project_id: 项目ID
    request: 批量删除请求，包含要删除的任务ID列表

Returns:
    批量删除结果
 * @summary Batch Delete Tasks
 */
export const batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost = (
	projectId: number,
	taskBatchDeleteRequest: TaskBatchDeleteRequest,
	signal?: AbortSignal,
) => {
	return customFetcher<TaskBatchDeleteResponse>({
		url: `/api/projects/${projectId}/tasks/batch-delete`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: taskBatchDeleteRequest,
		signal,
	});
};

export const getBatchDeleteTasksApiProjectsProjectIdTasksBatchDeletePostMutationOptions =
	<TError = HTTPValidationError, TContext = unknown>(options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<
					typeof batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost
				>
			>,
			TError,
			{ projectId: number; data: TaskBatchDeleteRequest },
			TContext
		>;
	}): UseMutationOptions<
		Awaited<
			ReturnType<
				typeof batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost
			>
		>,
		TError,
		{ projectId: number; data: TaskBatchDeleteRequest },
		TContext
	> => {
		const mutationKey = [
			"batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost",
		];
		const { mutation: mutationOptions } = options
			? options.mutation &&
				"mutationKey" in options.mutation &&
				options.mutation.mutationKey
				? options
				: { ...options, mutation: { ...options.mutation, mutationKey } }
			: { mutation: { mutationKey } };

		const mutationFn: MutationFunction<
			Awaited<
				ReturnType<
					typeof batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost
				>
			>,
			{ projectId: number; data: TaskBatchDeleteRequest }
		> = (props) => {
			const { projectId, data } = props ?? {};

			return batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost(
				projectId,
				data,
			);
		};

		return { mutationFn, ...mutationOptions };
	};

export type BatchDeleteTasksApiProjectsProjectIdTasksBatchDeletePostMutationResult =
	NonNullable<
		Awaited<
			ReturnType<
				typeof batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost
			>
		>
	>;
export type BatchDeleteTasksApiProjectsProjectIdTasksBatchDeletePostMutationBody =
	TaskBatchDeleteRequest;
export type BatchDeleteTasksApiProjectsProjectIdTasksBatchDeletePostMutationError =
	HTTPValidationError;

/**
 * @summary Batch Delete Tasks
 */
export const useBatchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<
					typeof batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost
				>
			>,
			TError,
			{ projectId: number; data: TaskBatchDeleteRequest },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<
		ReturnType<typeof batchDeleteTasksApiProjectsProjectIdTasksBatchDeletePost>
	>,
	TError,
	{ projectId: number; data: TaskBatchDeleteRequest },
	TContext
> => {
	const mutationOptions =
		getBatchDeleteTasksApiProjectsProjectIdTasksBatchDeletePostMutationOptions(
			options,
		);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 获取任务的进展记录列表

Args:
    project_id: 项目ID
    task_id: 任务ID
    limit: 返回数量限制
    offset: 偏移量

Returns:
    任务进展记录列表
 * @summary Get Task Progress
 */
export const getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet = (
	projectId: number,
	taskId: number,
	params?: GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetParams,
	signal?: AbortSignal,
) => {
	return customFetcher<TaskProgressListResponse>({
		url: `/api/projects/${projectId}/tasks/${taskId}/progress`,
		method: "GET",
		params,
		signal,
	});
};

export const getGetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetQueryKey =
	(
		projectId?: number,
		taskId?: number,
		params?: GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetParams,
	) => {
		return [
			`/api/projects/${projectId}/tasks/${taskId}/progress`,
			...(params ? [params] : []),
		] as const;
	};

export const getGetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetQueryOptions =
	<
		TData = Awaited<
			ReturnType<
				typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
			>
		>,
		TError = HTTPValidationError,
	>(
		projectId: number,
		taskId: number,
		params?: GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetParams,
		options?: {
			query?: Partial<
				UseQueryOptions<
					Awaited<
						ReturnType<
							typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
						>
					>,
					TError,
					TData
				>
			>;
		},
	) => {
		const { query: queryOptions } = options ?? {};

		const queryKey =
			queryOptions?.queryKey ??
			getGetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetQueryKey(
				projectId,
				taskId,
				params,
			);

		const queryFn: QueryFunction<
			Awaited<
				ReturnType<
					typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
				>
			>
		> = ({ signal }) =>
			getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet(
				projectId,
				taskId,
				params,
				signal,
			);

		return {
			queryKey,
			queryFn,
			enabled: !!(projectId && taskId),
			...queryOptions,
		} as UseQueryOptions<
			Awaited<
				ReturnType<
					typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
				>
			>,
			TError,
			TData
		> & { queryKey: DataTag<QueryKey, TData, TError> };
	};

export type GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetQueryResult =
	NonNullable<
		Awaited<
			ReturnType<
				typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
			>
		>
	>;
export type GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetQueryError =
	HTTPValidationError;

export function useGetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet<
	TData = Awaited<
		ReturnType<typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	params:
		| undefined
		| GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
					>
				>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<
						ReturnType<
							typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
						>
					>,
					TError,
					Awaited<
						ReturnType<
							typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
						>
					>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet<
	TData = Awaited<
		ReturnType<typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	params?: GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
					>
				>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<
						ReturnType<
							typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
						>
					>,
					TError,
					Awaited<
						ReturnType<
							typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
						>
					>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet<
	TData = Awaited<
		ReturnType<typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	params?: GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
					>
				>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Task Progress
 */

export function useGetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet<
	TData = Awaited<
		ReturnType<typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	params?: GetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getTaskProgressApiProjectsProjectIdTasksTaskIdProgressGet
					>
				>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getGetTaskProgressApiProjectsProjectIdTasksTaskIdProgressGetQueryOptions(
			projectId,
			taskId,
			params,
			options,
		);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 获取任务最新的进展记录

Args:
    project_id: 项目ID
    task_id: 任务ID

Returns:
    最新的进展记录，无记录返回null
 * @summary Get Task Progress Latest
 */
export const getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet =
	(projectId: number, taskId: number, signal?: AbortSignal) => {
		return customFetcher<GetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet200>(
			{
				url: `/api/projects/${projectId}/tasks/${taskId}/progress/latest`,
				method: "GET",
				signal,
			},
		);
	};

export const getGetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGetQueryKey =
	(projectId?: number, taskId?: number) => {
		return [
			`/api/projects/${projectId}/tasks/${taskId}/progress/latest`,
		] as const;
	};

export const getGetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGetQueryOptions =
	<
		TData = Awaited<
			ReturnType<
				typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
			>
		>,
		TError = HTTPValidationError,
	>(
		projectId: number,
		taskId: number,
		options?: {
			query?: Partial<
				UseQueryOptions<
					Awaited<
						ReturnType<
							typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
						>
					>,
					TError,
					TData
				>
			>;
		},
	) => {
		const { query: queryOptions } = options ?? {};

		const queryKey =
			queryOptions?.queryKey ??
			getGetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGetQueryKey(
				projectId,
				taskId,
			);

		const queryFn: QueryFunction<
			Awaited<
				ReturnType<
					typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
				>
			>
		> = ({ signal }) =>
			getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet(
				projectId,
				taskId,
				signal,
			);

		return {
			queryKey,
			queryFn,
			enabled: !!(projectId && taskId),
			...queryOptions,
		} as UseQueryOptions<
			Awaited<
				ReturnType<
					typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
				>
			>,
			TError,
			TData
		> & { queryKey: DataTag<QueryKey, TData, TError> };
	};

export type GetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGetQueryResult =
	NonNullable<
		Awaited<
			ReturnType<
				typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
			>
		>
	>;
export type GetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGetQueryError =
	HTTPValidationError;

export function useGetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet<
	TData = Awaited<
		ReturnType<
			typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
		>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
					>
				>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<
						ReturnType<
							typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
						>
					>,
					TError,
					Awaited<
						ReturnType<
							typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
						>
					>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet<
	TData = Awaited<
		ReturnType<
			typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
		>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
					>
				>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<
						ReturnType<
							typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
						>
					>,
					TError,
					Awaited<
						ReturnType<
							typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
						>
					>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet<
	TData = Awaited<
		ReturnType<
			typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
		>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
					>
				>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Task Progress Latest
 */

export function useGetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet<
	TData = Awaited<
		ReturnType<
			typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
		>
	>,
	TError = HTTPValidationError,
>(
	projectId: number,
	taskId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<
					ReturnType<
						typeof getTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGet
					>
				>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getGetTaskProgressLatestApiProjectsProjectIdTasksTaskIdProgressLatestGetQueryOptions(
			projectId,
			taskId,
			options,
		);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 手动触发生成任务进展摘要

Args:
    project_id: 项目ID
    task_id: 任务ID

Returns:
    生成的进展记录
 * @summary Generate Task Summary
 */
export const generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost =
	(projectId: number, taskId: number, signal?: AbortSignal) => {
		return customFetcher<TaskProgressResponse>({
			url: `/api/projects/${projectId}/tasks/${taskId}/generate-summary`,
			method: "POST",
			signal,
		});
	};

export const getGenerateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPostMutationOptions =
	<TError = HTTPValidationError, TContext = unknown>(options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<
					typeof generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost
				>
			>,
			TError,
			{ projectId: number; taskId: number },
			TContext
		>;
	}): UseMutationOptions<
		Awaited<
			ReturnType<
				typeof generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost
			>
		>,
		TError,
		{ projectId: number; taskId: number },
		TContext
	> => {
		const mutationKey = [
			"generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost",
		];
		const { mutation: mutationOptions } = options
			? options.mutation &&
				"mutationKey" in options.mutation &&
				options.mutation.mutationKey
				? options
				: { ...options, mutation: { ...options.mutation, mutationKey } }
			: { mutation: { mutationKey } };

		const mutationFn: MutationFunction<
			Awaited<
				ReturnType<
					typeof generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost
				>
			>,
			{ projectId: number; taskId: number }
		> = (props) => {
			const { projectId, taskId } = props ?? {};

			return generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost(
				projectId,
				taskId,
			);
		};

		return { mutationFn, ...mutationOptions };
	};

export type GenerateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPostMutationResult =
	NonNullable<
		Awaited<
			ReturnType<
				typeof generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost
			>
		>
	>;

export type GenerateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPostMutationError =
	HTTPValidationError;

/**
 * @summary Generate Task Summary
 */
export const useGenerateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost =
	<TError = HTTPValidationError, TContext = unknown>(
		options?: {
			mutation?: UseMutationOptions<
				Awaited<
					ReturnType<
						typeof generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost
					>
				>,
				TError,
				{ projectId: number; taskId: number },
				TContext
			>;
		},
		queryClient?: QueryClient,
	): UseMutationResult<
		Awaited<
			ReturnType<
				typeof generateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPost
			>
		>,
		TError,
		{ projectId: number; taskId: number },
		TContext
	> => {
		const mutationOptions =
			getGenerateTaskSummaryApiProjectsProjectIdTasksTaskIdGenerateSummaryPostMutationOptions(
				options,
			);

		return useMutation(mutationOptions, queryClient);
	};
