/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetcher } from ".././fetcher";
import type {
	ContextListResponse,
	ContextResponse,
	ContextUpdateRequest,
	GetContextsApiContextsGetParams,
	HTTPValidationError,
} from ".././schemas";

/**
 * 获取上下文记录列表

Args:
    associated: 是否已关联任务（None表示全部，false表示未关联，true表示已关联）
    task_id: 按任务ID过滤
    limit: 返回数量限制
    offset: 偏移量

Returns:
    上下文记录列表

Examples:
    GET /api/contexts?associated=false  # 获取所有未关联的上下文
    GET /api/contexts?associated=true   # 获取所有已关联的上下文
    GET /api/contexts?task_id=1         # 获取关联到任务1的所有上下文
    GET /api/contexts                   # 获取所有上下文
 * @summary Get Contexts
 */
export const getContextsApiContextsGet = (
	params?: GetContextsApiContextsGetParams,
	signal?: AbortSignal,
) => {
	return customFetcher<ContextListResponse>({
		url: `/api/contexts`,
		method: "GET",
		params,
		signal,
	});
};

export const getGetContextsApiContextsGetQueryKey = (
	params?: GetContextsApiContextsGetParams,
) => {
	return [`/api/contexts`, ...(params ? [params] : [])] as const;
};

export const getGetContextsApiContextsGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getContextsApiContextsGet>>,
	TError = HTTPValidationError,
>(
	params?: GetContextsApiContextsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextsApiContextsGet>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetContextsApiContextsGetQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getContextsApiContextsGet>>
	> = ({ signal }) => getContextsApiContextsGet(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getContextsApiContextsGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContextsApiContextsGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getContextsApiContextsGet>>
>;
export type GetContextsApiContextsGetQueryError = HTTPValidationError;

export function useGetContextsApiContextsGet<
	TData = Awaited<ReturnType<typeof getContextsApiContextsGet>>,
	TError = HTTPValidationError,
>(
	params: undefined | GetContextsApiContextsGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextsApiContextsGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getContextsApiContextsGet>>,
					TError,
					Awaited<ReturnType<typeof getContextsApiContextsGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContextsApiContextsGet<
	TData = Awaited<ReturnType<typeof getContextsApiContextsGet>>,
	TError = HTTPValidationError,
>(
	params?: GetContextsApiContextsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextsApiContextsGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getContextsApiContextsGet>>,
					TError,
					Awaited<ReturnType<typeof getContextsApiContextsGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContextsApiContextsGet<
	TData = Awaited<ReturnType<typeof getContextsApiContextsGet>>,
	TError = HTTPValidationError,
>(
	params?: GetContextsApiContextsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextsApiContextsGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Contexts
 */

export function useGetContextsApiContextsGet<
	TData = Awaited<ReturnType<typeof getContextsApiContextsGet>>,
	TError = HTTPValidationError,
>(
	params?: GetContextsApiContextsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextsApiContextsGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetContextsApiContextsGetQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 获取单个上下文记录详情

Args:
    context_id: 上下文ID

Returns:
    上下文记录详情
 * @summary Get Context
 */
export const getContextApiContextsContextIdGet = (
	contextId: number,
	signal?: AbortSignal,
) => {
	return customFetcher<ContextResponse>({
		url: `/api/contexts/${contextId}`,
		method: "GET",
		signal,
	});
};

export const getGetContextApiContextsContextIdGetQueryKey = (
	contextId?: number,
) => {
	return [`/api/contexts/${contextId}`] as const;
};

export const getGetContextApiContextsContextIdGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
	TError = HTTPValidationError,
>(
	contextId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetContextApiContextsContextIdGetQueryKey(contextId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>
	> = ({ signal }) => getContextApiContextsContextIdGet(contextId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!contextId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContextApiContextsContextIdGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>
>;
export type GetContextApiContextsContextIdGetQueryError = HTTPValidationError;

export function useGetContextApiContextsContextIdGet<
	TData = Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
	TError = HTTPValidationError,
>(
	contextId: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
					TError,
					Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContextApiContextsContextIdGet<
	TData = Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
	TError = HTTPValidationError,
>(
	contextId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
					TError,
					Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContextApiContextsContextIdGet<
	TData = Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
	TError = HTTPValidationError,
>(
	contextId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Context
 */

export function useGetContextApiContextsContextIdGet<
	TData = Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
	TError = HTTPValidationError,
>(
	contextId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getContextApiContextsContextIdGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetContextApiContextsContextIdGetQueryOptions(
		contextId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 更新上下文记录的任务关联

Args:
    context_id: 上下文ID
    update_data: 更新数据，包含task_id

Returns:
    更新后的上下文记录

Examples:
    PUT /api/contexts/1
    Body: {"task_id": 5}  # 将上下文1关联到任务5

    PUT /api/contexts/1
    Body: {"task_id": null}  # 解除上下文1的任务关联
 * @summary Update Context
 */
export const updateContextApiContextsContextIdPut = (
	contextId: number,
	contextUpdateRequest: ContextUpdateRequest,
) => {
	return customFetcher<ContextResponse>({
		url: `/api/contexts/${contextId}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: contextUpdateRequest,
	});
};

export const getUpdateContextApiContextsContextIdPutMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateContextApiContextsContextIdPut>>,
		TError,
		{ contextId: number; data: ContextUpdateRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateContextApiContextsContextIdPut>>,
	TError,
	{ contextId: number; data: ContextUpdateRequest },
	TContext
> => {
	const mutationKey = ["updateContextApiContextsContextIdPut"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateContextApiContextsContextIdPut>>,
		{ contextId: number; data: ContextUpdateRequest }
	> = (props) => {
		const { contextId, data } = props ?? {};

		return updateContextApiContextsContextIdPut(contextId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateContextApiContextsContextIdPutMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateContextApiContextsContextIdPut>>
>;
export type UpdateContextApiContextsContextIdPutMutationBody =
	ContextUpdateRequest;
export type UpdateContextApiContextsContextIdPutMutationError =
	HTTPValidationError;

/**
 * @summary Update Context
 */
export const useUpdateContextApiContextsContextIdPut = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateContextApiContextsContextIdPut>>,
			TError,
			{ contextId: number; data: ContextUpdateRequest },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateContextApiContextsContextIdPut>>,
	TError,
	{ contextId: number; data: ContextUpdateRequest },
	TContext
> => {
	const mutationOptions =
		getUpdateContextApiContextsContextIdPutMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
