/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { customFetcher } from ".././fetcher";
import type {
	HTTPValidationError,
	VisionChatRequest,
	VisionChatResponse,
} from ".././schemas";

/**
 * 视觉多模态聊天接口

使用通义千问视觉模型分析多张截图，支持文本提示词。

Args:
    request: 视觉聊天请求，包含截图ID列表和提示词

Returns:
    视觉聊天响应，包含模型生成的文本和元信息

Raises:
    HTTPException: 当请求参数无效或API调用失败时
 * @summary Vision Chat
 */
export const visionChatApiVisionChatPost = (
	visionChatRequest: VisionChatRequest,
	signal?: AbortSignal,
) => {
	return customFetcher<VisionChatResponse>({
		url: `/api/vision/chat`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: visionChatRequest,
		signal,
	});
};

export const getVisionChatApiVisionChatPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof visionChatApiVisionChatPost>>,
		TError,
		{ data: VisionChatRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof visionChatApiVisionChatPost>>,
	TError,
	{ data: VisionChatRequest },
	TContext
> => {
	const mutationKey = ["visionChatApiVisionChatPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof visionChatApiVisionChatPost>>,
		{ data: VisionChatRequest }
	> = (props) => {
		const { data } = props ?? {};

		return visionChatApiVisionChatPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type VisionChatApiVisionChatPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof visionChatApiVisionChatPost>>
>;
export type VisionChatApiVisionChatPostMutationBody = VisionChatRequest;
export type VisionChatApiVisionChatPostMutationError = HTTPValidationError;

/**
 * @summary Vision Chat
 */
export const useVisionChatApiVisionChatPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof visionChatApiVisionChatPost>>,
			TError,
			{ data: VisionChatRequest },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof visionChatApiVisionChatPost>>,
	TError,
	{ data: VisionChatRequest },
	TContext
> => {
	const mutationOptions =
		getVisionChatApiVisionChatPostMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
