/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetcher } from ".././fetcher";
import type {
	GenerateTasksResponse,
	GetProjectsApiProjectsGetParams,
	HTTPValidationError,
	ProjectCreate,
	ProjectListResponse,
	ProjectResponse,
	ProjectUpdate,
} from ".././schemas";

/**
 * 创建新项目

Args:
    project: 项目创建信息

Returns:
    创建的项目信息
 * @summary Create Project
 */
export const createProjectApiProjectsPost = (
	projectCreate: ProjectCreate,
	signal?: AbortSignal,
) => {
	return customFetcher<ProjectResponse>({
		url: `/api/projects`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: projectCreate,
		signal,
	});
};

export const getCreateProjectApiProjectsPostMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createProjectApiProjectsPost>>,
		TError,
		{ data: ProjectCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createProjectApiProjectsPost>>,
	TError,
	{ data: ProjectCreate },
	TContext
> => {
	const mutationKey = ["createProjectApiProjectsPost"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createProjectApiProjectsPost>>,
		{ data: ProjectCreate }
	> = (props) => {
		const { data } = props ?? {};

		return createProjectApiProjectsPost(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateProjectApiProjectsPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof createProjectApiProjectsPost>>
>;
export type CreateProjectApiProjectsPostMutationBody = ProjectCreate;
export type CreateProjectApiProjectsPostMutationError = HTTPValidationError;

/**
 * @summary Create Project
 */
export const useCreateProjectApiProjectsPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createProjectApiProjectsPost>>,
			TError,
			{ data: ProjectCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createProjectApiProjectsPost>>,
	TError,
	{ data: ProjectCreate },
	TContext
> => {
	const mutationOptions =
		getCreateProjectApiProjectsPostMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 获取所有项目列表

Args:
    limit: 返回数量限制
    offset: 偏移量
    status: 项目状态筛选

Returns:
    项目列表
 * @summary Get Projects
 */
export const getProjectsApiProjectsGet = (
	params?: GetProjectsApiProjectsGetParams,
	signal?: AbortSignal,
) => {
	return customFetcher<ProjectListResponse>({
		url: `/api/projects`,
		method: "GET",
		params,
		signal,
	});
};

export const getGetProjectsApiProjectsGetQueryKey = (
	params?: GetProjectsApiProjectsGetParams,
) => {
	return [`/api/projects`, ...(params ? [params] : [])] as const;
};

export const getGetProjectsApiProjectsGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
	TError = HTTPValidationError,
>(
	params?: GetProjectsApiProjectsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetProjectsApiProjectsGetQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getProjectsApiProjectsGet>>
	> = ({ signal }) => getProjectsApiProjectsGet(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectsApiProjectsGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getProjectsApiProjectsGet>>
>;
export type GetProjectsApiProjectsGetQueryError = HTTPValidationError;

export function useGetProjectsApiProjectsGet<
	TData = Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
	TError = HTTPValidationError,
>(
	params: undefined | GetProjectsApiProjectsGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
					TError,
					Awaited<ReturnType<typeof getProjectsApiProjectsGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectsApiProjectsGet<
	TData = Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
	TError = HTTPValidationError,
>(
	params?: GetProjectsApiProjectsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
					TError,
					Awaited<ReturnType<typeof getProjectsApiProjectsGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectsApiProjectsGet<
	TData = Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
	TError = HTTPValidationError,
>(
	params?: GetProjectsApiProjectsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Projects
 */

export function useGetProjectsApiProjectsGet<
	TData = Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
	TError = HTTPValidationError,
>(
	params?: GetProjectsApiProjectsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectsApiProjectsGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetProjectsApiProjectsGetQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 获取单个项目详情

Args:
    project_id: 项目ID

Returns:
    项目详情
 * @summary Get Project
 */
export const getProjectApiProjectsProjectIdGet = (
	projectId: number,
	signal?: AbortSignal,
) => {
	return customFetcher<ProjectResponse>({
		url: `/api/projects/${projectId}`,
		method: "GET",
		signal,
	});
};

export const getGetProjectApiProjectsProjectIdGetQueryKey = (
	projectId?: number,
) => {
	return [`/api/projects/${projectId}`] as const;
};

export const getGetProjectApiProjectsProjectIdGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetProjectApiProjectsProjectIdGetQueryKey(projectId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>
	> = ({ signal }) => getProjectApiProjectsProjectIdGet(projectId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!projectId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectApiProjectsProjectIdGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>
>;
export type GetProjectApiProjectsProjectIdGetQueryError = HTTPValidationError;

export function useGetProjectApiProjectsProjectIdGet<
	TData = Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
					TError,
					Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectApiProjectsProjectIdGet<
	TData = Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
					TError,
					Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectApiProjectsProjectIdGet<
	TData = Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project
 */

export function useGetProjectApiProjectsProjectIdGet<
	TData = Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
	TError = HTTPValidationError,
>(
	projectId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getProjectApiProjectsProjectIdGet>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetProjectApiProjectsProjectIdGetQueryOptions(
		projectId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 更新项目

Args:
    project_id: 项目ID
    project: 项目更新信息

Returns:
    更新后的项目信息
 * @summary Update Project
 */
export const updateProjectApiProjectsProjectIdPut = (
	projectId: number,
	projectUpdate: ProjectUpdate,
) => {
	return customFetcher<ProjectResponse>({
		url: `/api/projects/${projectId}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: projectUpdate,
	});
};

export const getUpdateProjectApiProjectsProjectIdPutMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateProjectApiProjectsProjectIdPut>>,
		TError,
		{ projectId: number; data: ProjectUpdate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateProjectApiProjectsProjectIdPut>>,
	TError,
	{ projectId: number; data: ProjectUpdate },
	TContext
> => {
	const mutationKey = ["updateProjectApiProjectsProjectIdPut"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateProjectApiProjectsProjectIdPut>>,
		{ projectId: number; data: ProjectUpdate }
	> = (props) => {
		const { projectId, data } = props ?? {};

		return updateProjectApiProjectsProjectIdPut(projectId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateProjectApiProjectsProjectIdPutMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateProjectApiProjectsProjectIdPut>>
>;
export type UpdateProjectApiProjectsProjectIdPutMutationBody = ProjectUpdate;
export type UpdateProjectApiProjectsProjectIdPutMutationError =
	HTTPValidationError;

/**
 * @summary Update Project
 */
export const useUpdateProjectApiProjectsProjectIdPut = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateProjectApiProjectsProjectIdPut>>,
			TError,
			{ projectId: number; data: ProjectUpdate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateProjectApiProjectsProjectIdPut>>,
	TError,
	{ projectId: number; data: ProjectUpdate },
	TContext
> => {
	const mutationOptions =
		getUpdateProjectApiProjectsProjectIdPutMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * 删除项目

Args:
    project_id: 项目ID

Returns:
    无返回内容
 * @summary Delete Project
 */
export const deleteProjectApiProjectsProjectIdDelete = (projectId: number) => {
	return customFetcher<void>({
		url: `/api/projects/${projectId}`,
		method: "DELETE",
	});
};

export const getDeleteProjectApiProjectsProjectIdDeleteMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteProjectApiProjectsProjectIdDelete>>,
		TError,
		{ projectId: number },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteProjectApiProjectsProjectIdDelete>>,
	TError,
	{ projectId: number },
	TContext
> => {
	const mutationKey = ["deleteProjectApiProjectsProjectIdDelete"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteProjectApiProjectsProjectIdDelete>>,
		{ projectId: number }
	> = (props) => {
		const { projectId } = props ?? {};

		return deleteProjectApiProjectsProjectIdDelete(projectId);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteProjectApiProjectsProjectIdDeleteMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteProjectApiProjectsProjectIdDelete>>
>;

export type DeleteProjectApiProjectsProjectIdDeleteMutationError =
	HTTPValidationError;

/**
 * @summary Delete Project
 */
export const useDeleteProjectApiProjectsProjectIdDelete = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteProjectApiProjectsProjectIdDelete>>,
			TError,
			{ projectId: number },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteProjectApiProjectsProjectIdDelete>>,
	TError,
	{ projectId: number },
	TContext
> => {
	const mutationOptions =
		getDeleteProjectApiProjectsProjectIdDeleteMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * AI任务拆解：根据项目信息自动生成任务列表

Args:
    project_id: 项目ID

Returns:
    生成的任务列表
 * @summary Generate Tasks
 */
export const generateTasksApiProjectsProjectIdGenerateTasksPost = (
	projectId: number,
	signal?: AbortSignal,
) => {
	return customFetcher<GenerateTasksResponse>({
		url: `/api/projects/${projectId}/generate-tasks`,
		method: "POST",
		signal,
	});
};

export const getGenerateTasksApiProjectsProjectIdGenerateTasksPostMutationOptions =
	<TError = HTTPValidationError, TContext = unknown>(options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<typeof generateTasksApiProjectsProjectIdGenerateTasksPost>
			>,
			TError,
			{ projectId: number },
			TContext
		>;
	}): UseMutationOptions<
		Awaited<
			ReturnType<typeof generateTasksApiProjectsProjectIdGenerateTasksPost>
		>,
		TError,
		{ projectId: number },
		TContext
	> => {
		const mutationKey = ["generateTasksApiProjectsProjectIdGenerateTasksPost"];
		const { mutation: mutationOptions } = options
			? options.mutation &&
				"mutationKey" in options.mutation &&
				options.mutation.mutationKey
				? options
				: { ...options, mutation: { ...options.mutation, mutationKey } }
			: { mutation: { mutationKey } };

		const mutationFn: MutationFunction<
			Awaited<
				ReturnType<typeof generateTasksApiProjectsProjectIdGenerateTasksPost>
			>,
			{ projectId: number }
		> = (props) => {
			const { projectId } = props ?? {};

			return generateTasksApiProjectsProjectIdGenerateTasksPost(projectId);
		};

		return { mutationFn, ...mutationOptions };
	};

export type GenerateTasksApiProjectsProjectIdGenerateTasksPostMutationResult =
	NonNullable<
		Awaited<
			ReturnType<typeof generateTasksApiProjectsProjectIdGenerateTasksPost>
		>
	>;

export type GenerateTasksApiProjectsProjectIdGenerateTasksPostMutationError =
	HTTPValidationError;

/**
 * @summary Generate Tasks
 */
export const useGenerateTasksApiProjectsProjectIdGenerateTasksPost = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<
				ReturnType<typeof generateTasksApiProjectsProjectIdGenerateTasksPost>
			>,
			TError,
			{ projectId: number },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<
		ReturnType<typeof generateTasksApiProjectsProjectIdGenerateTasksPost>
	>,
	TError,
	{ projectId: number },
	TContext
> => {
	const mutationOptions =
		getGenerateTasksApiProjectsProjectIdGenerateTasksPostMutationOptions(
			options,
		);

	return useMutation(mutationOptions, queryClient);
};
