/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type { ActivityResponseAiSummary } from "./activityResponseAiSummary";
import type { ActivityResponseAiTitle } from "./activityResponseAiTitle";
import type { ActivityResponseCreatedAt } from "./activityResponseCreatedAt";
import type { ActivityResponseUpdatedAt } from "./activityResponseUpdatedAt";

export interface ActivityResponse {
	id: number;
	start_time: string;
	end_time: string;
	ai_title?: ActivityResponseAiTitle;
	ai_summary?: ActivityResponseAiSummary;
	event_count: number;
	created_at?: ActivityResponseCreatedAt;
	updated_at?: ActivityResponseUpdatedAt;
}
