/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */
import type { ChatMessageConversationId } from "./chatMessageConversationId";
import type { ChatMessageProjectId } from "./chatMessageProjectId";
import type { ChatMessageTaskIds } from "./chatMessageTaskIds";

export interface ChatMessage {
	message: string;
	conversation_id?: ChatMessageConversationId;
	project_id?: ChatMessageProjectId;
	task_ids?: ChatMessageTaskIds;
	use_rag?: boolean;
}
