/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */
import type { EventResponse } from "./eventResponse";

/**
 * 事件列表响应，包含事件列表和总数
 */
export interface EventListResponse {
	events: EventResponse[];
	total_count: number;
}
