/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type { ExtractedTodoConfidence } from "./extractedTodoConfidence";
import type { ExtractedTodoDescription } from "./extractedTodoDescription";
import type { ExtractedTodoScheduledTime } from "./extractedTodoScheduledTime";
import type { TodoTimeInfo } from "./todoTimeInfo";

/**
 * 提取的待办项结构
 */
export interface ExtractedTodo {
	/**
	 * 待办标题
	 * @minLength 1
	 * @maxLength 100
	 */
	title: string;
	/** 待办描述（可选） */
	description?: ExtractedTodoDescription;
	/** 时间信息 */
	time_info: TodoTimeInfo;
	/** 解析后的绝对时间（程序计算得出） */
	scheduled_time?: ExtractedTodoScheduledTime;
	/** 来源文本片段，用于验证 */
	source_text: string;
	/** 置信度（0.0-1.0），可选 */
	confidence?: ExtractedTodoConfidence;
	/** 相关的截图ID列表 */
	screenshot_ids?: number[];
}
