/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 创建日记请求模型
 */
export interface JournalCreate {
	/**
	 * 日记标题
	 * @minLength 1
	 * @maxLength 200
	 */
	name: string;
	/** 日记内容（富文本） */
	user_notes: string;
	/** 日记日期 */
	date: string;
	/**
	 * 内容格式：markdown/html/json
	 * @maxLength 20
	 */
	content_format?: string;
	/** 关联的标签ID列表 */
	tag_ids?: number[];
}
