/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type { JournalUpdateContentFormat } from "./journalUpdateContentFormat";
import type { JournalUpdateDate } from "./journalUpdateDate";
import type { JournalUpdateName } from "./journalUpdateName";
import type { JournalUpdateTagIds } from "./journalUpdateTagIds";
import type { JournalUpdateUserNotes } from "./journalUpdateUserNotes";

/**
 * 更新日记请求模型
 */
export interface JournalUpdate {
	/** 日记标题 */
	name?: JournalUpdateName;
	/** 日记内容（富文本） */
	user_notes?: JournalUpdateUserNotes;
	/** 日记日期 */
	date?: JournalUpdateDate;
	/** 内容格式：markdown/html/json */
	content_format?: JournalUpdateContentFormat;
	/** 关联的标签ID列表（覆盖替换） */
	tag_ids?: JournalUpdateTagIds;
}
