/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type { PlanQuestionnaireRequestSessionId } from "./planQuestionnaireRequestSessionId";
import type { PlanQuestionnaireRequestTodoId } from "./planQuestionnaireRequestTodoId";

export interface PlanQuestionnaireRequest {
	todo_name: string;
	todo_id?: PlanQuestionnaireRequestTodoId;
	session_id?: PlanQuestionnaireRequestSessionId;
}
