/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */
import type { ScreenshotResponseAppName } from "./screenshotResponseAppName";
import type { ScreenshotResponseTextContent } from "./screenshotResponseTextContent";
import type { ScreenshotResponseWindowTitle } from "./screenshotResponseWindowTitle";

export interface ScreenshotResponse {
	id: number;
	file_path: string;
	app_name: ScreenshotResponseAppName;
	window_title: ScreenshotResponseWindowTitle;
	created_at: string;
	text_content: ScreenshotResponseTextContent;
	width: number;
	height: number;
	file_deleted?: boolean;
}
