/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type { SearchRequestAppName } from "./searchRequestAppName";
import type { SearchRequestEndDate } from "./searchRequestEndDate";
import type { SearchRequestQuery } from "./searchRequestQuery";
import type { SearchRequestStartDate } from "./searchRequestStartDate";

export interface SearchRequest {
	query?: SearchRequestQuery;
	start_date?: SearchRequestStartDate;
	end_date?: SearchRequestEndDate;
	app_name?: SearchRequestAppName;
	limit?: number;
}
