/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

import type { ProcessInfo } from "./processInfo";
import type { SystemResourcesResponseCpu } from "./systemResourcesResponseCpu";
import type { SystemResourcesResponseDisk } from "./systemResourcesResponseDisk";
import type { SystemResourcesResponseMemory } from "./systemResourcesResponseMemory";
import type { SystemResourcesResponseStorage } from "./systemResourcesResponseStorage";
import type { SystemResourcesResponseSummary } from "./systemResourcesResponseSummary";

export interface SystemResourcesResponse {
	memory: SystemResourcesResponseMemory;
	cpu: SystemResourcesResponseCpu;
	disk: SystemResourcesResponseDisk;
	lifetrace_processes: ProcessInfo[];
	storage: SystemResourcesResponseStorage;
	summary: SystemResourcesResponseSummary;
	timestamp: string;
}
