/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * LifeTrace API
 * 智能生活记录系统 API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Todo 优先级（与前端保持一致）
 */
export type TodoPriority = (typeof TodoPriority)[keyof typeof TodoPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TodoPriority = {
	high: "high",
	medium: "medium",
	low: "low",
	none: "none",
} as const;
